### ISSUE TITLE
VMM + OVS : Error starting domain: error creating macvtap interface macvtap0@vport5 (52:54:00:55:18:e7): Device or resource busy

### ISSUE THREAD

**Issue by Noctis-LucisCaelum** [openvswitch/ovs-issues#140]
Hello, thanks for your attention.

I would like to kindly request support/advice/feedback about an issue that I am having with the Virtual Machine Manager and OpenVSwitch.

I am deploying 7 Virtual Machines (Virtual Machine Manager 1.4.1, CentOS 7) and need to connect them to an OpenVSwitch (2.5.2)  bridge for SDN purposes.

I installed OVS without any complications following this guide: https://gist.github.com/umardx/a31bf6a13600a55c0d07d4ca33133834

Later on, I created an OVS bridge with 7 ports, each one for my 7 VMs, following this very clear tutorial: https://www.youtube.com/watch?v=rYW7kQRyUvA

At the moment I Power On any of the 7 VMs I get the following error:

Error starting domain: error creating macvtap interface macvtap0@vport5 (52:54:00:55:18:e7): Device or resource busy

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 88, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 124, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 83, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1489, in startup
    self._backend.create()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1039, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: error creating macvtap interface macvtap0@vport5 (52:54:00:55:18:e7): Device or resource busy

I've tried cloning the VMs thinking that adding the network interface later after creating the VM was the problem but the error continues to show up.

In addition I restarted the OVS service and the result is the same.

Thanks in advance for your attention, I apologize if this is not the correct channel to escalate this error, and would appreciate that you point me where I should direct it to.

**Comment by jakevossen5** [comment]
Same issue. Where you able find a fix?

**Comment by tanmoysinha** [comment]
@Noctis-LucisCaelum I will take a look into this issue on a CentOS instance. You may check this https://bugzilla.redhat.com/show_bug.cgi?id=1611044, wherein it says ovs allows to add an non-existing port to a bridge (i.e. an interface for which kernel has no entry) and then throws this error if you haven't added the tap ports physically using "ip tuntap add ......" , yet attempt to start the VM. 
So can you dump-the output of the command "ovs-vsctl show" and "ovs-ofctl show <bridge-name>" here?

**Comment by harunaadoga** [comment]
> Hello, thanks for your attention.
> 
> I would like to kindly request support/advice/feedback about an issue that I am having with the Virtual Machine Manager and OpenVSwitch.
> 
> I am deploying 7 Virtual Machines (Virtual Machine Manager 1.4.1, CentOS 7) and need to connect them to an OpenVSwitch (2.5.2) bridge for SDN purposes.
> 
> I installed OVS without any complications following this guide: https://gist.github.com/umardx/a31bf6a13600a55c0d07d4ca33133834
> 
> Later on, I created an OVS bridge with 7 ports, each one for my 7 VMs, following this very clear tutorial: https://www.youtube.com/watch?v=rYW7kQRyUvA
> 
> At the moment I Power On any of the 7 VMs I get the following error:
> 
> Error starting domain: error creating macvtap interface macvtap0@vport5 (52:54:00:55:18:e7): Device or resource busy
> 
> Traceback (most recent call last): File "/usr/share/virt-manager/virtManager/asyncjob.py", line 88, in cb_wrapper callback(asyncjob, *args, **kwargs) File "/usr/share/virt-manager/virtManager/asyncjob.py", line 124, in tmpcb callback(*args, **kwargs) File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 83, in newfn ret = fn(self, *args, **kwargs) File "/usr/share/virt-manager/virtManager/domain.py", line 1489, in startup self._backend.create() File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1039, in create if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self) libvirtError: error creating macvtap interface macvtap0@vport5 (52:54:00:55:18:e7): Device or resource busy
> 
> I've tried cloning the VMs thinking that adding the network interface later after creating the VM was the problem but the error continues to show up.
> 
> In addition I restarted the OVS service and the result is the same.
> 
> Thanks in advance for your attention, I apologize if this is not the correct channel to escalate this error, and would appreciate that you point me where I should direct it to.

Hello, please is there any update on this? I am currently facing the same problem with VMM+OvS on Ubuntu 20.04. All my virtual ports exist and not in use but I get the same error when I try to start my VMs.

**Comment by Noctis-LucisCaelum** [comment]
No idea, I've been detached from this project for 2 years, no longer
working on SDN. Last time we got something working was on Ubuntu, using
GNS3 and Cisco IOS. OpenVSwitch never made it to the final implementation
for lack of community support.

Good luck in your endeavors.

**Comment by igsilya** [comment]
Hi.  This seems to be exactly the same question asked on the ovs-discuss mailing list: https://mail.openvswitch.org/pipermail/ovs-discuss/2018-January/046076.html  and it seems that the author found some solution.
In general, the problem looks like a VM misconfiguration or a bug in VMM.
