### ISSUE TITLE
flow stats reset_counts OpenFlow1.5 FAILED

### ISSUE THREAD

**Issue by greenpau** [openvswitch/ovs-issues#149]
@blp , OF tests need to be adjusted for `hard_age=0,`.

During running the tests encountered the following:

```
251: OFPST_FLOW reply - OF1.5                        FAILED (ofp-print.at:1504)
ofproto-dpif
1165: ofproto-dpif - sFlow packet sampling - LACP structures ok
1181: ofproto-dpif - flow stats reset_counts OpenFlow1.5 FAILED (ofproto-dpif.at:7315)
ofproto-dpif - flow translation resource limits
1243: ofproto-dpif - in place modification (vlan)     FAILED (ofproto-dpif.at:9094)



Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
## ------------------------------ ##
## openvswitch 2.9.90 test suite. ##
## ------------------------------ ##
ofp-print
251: OFPST_FLOW reply - OF1.5                        FAILED (ofp-print.at:1504)
ofproto-dpif
1181: ofproto-dpif - flow stats reset_counts OpenFlow1.5 FAILED (ofproto-dpif.at:7315)




## ------------------------------ ##
## openvswitch 2.9.90 test suite. ##
## ------------------------------ ##
ofp-print
251: OFPST_FLOW reply - OF1.5                        FAILED (ofp-print.at:1504)
ofproto-dpif
1181: ofproto-dpif - flow stats reset_counts OpenFlow1.5 FAILED (ofproto-dpif.at:7315)
ofproto-dpif - flow translation resource limits
1243: ofproto-dpif - in place modification (vlan)     ok
```

Then, went to look at https://github.com/openvswitch/ovs/blob/master/tests/ofp-print.at#L1504-L1525

Re-run the command myself:

```bash
# utilities/ovs-ofctl ofp-print "\
> 06 13 01 00 00 00 00 04 00 01 00 00 00 00 00 00 \
> 00 78 00 00 00 00 80 00 00 00 00 00 00 05 00 00 \
> 00 00 00 00 00 00 00 00 00 01 00 0c 80 00 00 04 \
> 00 00 00 02 00 00 00 00 00 00 00 34 80 02 00 08 \
> 00 00 00 c4 0b 06 e0 40 80 02 02 08 00 00 00 c4 \
> 00 00 00 00 80 02 08 08 00 00 00 00 00 00 00 02 \
> 80 02 0a 08 00 00 00 00 00 00 00 80 00 00 00 00 \
> 00 04 00 18 00 00 00 00 00 00 00 10 ff ff ff fa \
> 00 00 00 00 00 00 00 00 00 78 00 00 00 00 0f a0 \
> 00 00 00 00 00 05 00 00 00 00 00 00 00 00 00 00 \
> 00 01 00 0c 80 00 00 04 00 00 00 03 00 00 00 00 \
> 00 00 00 34 80 02 00 08 00 00 00 b3 25 40 be 40 \
> 80 02 02 08 00 00 00 b3 00 00 00 00 80 02 08 08 \
> 00 00 00 00 00 00 00 02 80 02 0a 08 00 00 00 00 \
> 00 00 00 80 00 00 00 00 00 04 00 18 00 00 00 00 \
> 00 00 00 10 ff ff ff fa 00 00 00 00 00 00 00 00 \
> "
OFPST_FLOW reply (OF1.5) (xid=0x4):
 cookie=0x0, duration=196.185s, table=0, n_packets=2, n_bytes=128, send_flow_rem reset_counts idle_age=196, hard_age=0, in_port=2 actions=NORMAL
 cookie=0x0, duration=179.625s, table=0, n_packets=2, n_bytes=128, send_flow_rem reset_counts idle_age=179, hard_age=0, priority=4000,in_port=3 actions=NORMAL
```

As you can see `hard_age=0` is not expected by the test.

**Comment by blp** [comment]
Thanks for the report.  I posted a fix for review: https://patchwork.ozlabs.org/patch/919399/

**Comment by blp** [comment]
I applied the fix to master.
